### ISSUE TITLE
Configurable Caves Aging script

### ISSUE THREAD

**Issue by imDaniX** [imDaniX/Dangerous-Caves-2#12]
Thinking about a new user-defined system. With a new async calculation I can use more its power.
Idea is simple: user specifies list of block, type of action to do, its chance and some additional data.
```yaml
grow-vines:
  blocks: [] \\ Any solid block
  chance: 12.5
  action: vines
replace-stone:
  blocks:
    - stone
  chance: 33.33
  action: replace
  with:
    - andisite
    - cobblestone
moss-cobblestone:
  blocks:
    - cobblestone
  chance: 12.5
  action: replace
  with:
    - mossy_cobblestone
replace-andesite:
  blocks:
    - andesite
  chance: 50
  action: replace
  with:
    - granite
    - diorite
back-to-loop:
  blocks:
    - granite
    - andesite
    - cobblestone_wall
  chance: 10
  action: replace
  with:
    - stone
mushrooms:
  blocks:
    - stone
    - dirt
    - cobblestone
    - diorite
    - granite
    - andesite
  chance: 11.11
  action: mushroom
rocks:
  blocks:
    - stone
    - dirt
    - cobblestone
    - diorite
    - granite
    - andesite
  chance: 16.7
  action: rock
stalagmites:
  blocks:
    - stone
    - dirt
    - cobblestone
    - diorite
    - granite
    - andesite
  chance: 12.5
  action: stalagmite
```
The only problem is the size of configuration, so, maybe its better to transit it to another configuration file. Also I'm not sure if it should be hardcoded into the plugin or let users do everything by themselves.
