### ISSUE TITLE
New custom structures

### ISSUE THREAD

**Issue by imDaniX** [imDaniX/Dangerous-Caves-2#37]
Right now everything regarding structures is hardcoded. I guess the easiest way to fix the problem is to use schematics with some configuration for it. Something like
```yaml
# Just a name of the structure
structure-name:
  # Schematic file of this strucutre
  file: structure.schematic
  # Weight of this structure
  priority: 1
  # Replace blocks with other ones
  replace:
    # Block to replace
    PINK_WOOL:
      # REPLACEMENT: priority
      COBBLESTONE: 4
      STONE: 4
      COAL_ORE: 1
  # Allow to rotate and mirror the structure
  rotate: true
  # Change spawner types inside of structure
  spawners:
    # MOB_TYPE: priority
    # DC mobs are allowed
    smoke-demon: 1
    CAVE_SPIDER: 9
  # Some chest properties
  chests:
    loot: # TODO
    # Chance of spawning mimic instead of normal chest
    mimic: 10
```
Also might try to create some custom file type to store structures, just because I'm not sure if I want to store NBT data and such for this project.
